import IProduct from './interfaces/productInterface'

const products: IProduct[] = [
  {
    id: 1,
    title: 'iPhone 15 128GB Blue',
    price: 989.99,
    image: 'https://i.imgur.com/0ehfIwO.jpg',
    description:
      'Upoznajte iPhone 15 u predivnoj plavoj boji s prostranim prostorom za pohranu od 128GB - savršen spoj elegantnog dizajna i visoke funkcionalnosti. Ovaj izuzetan pametni telefon donosi vrhunski doživljaj korisnika uz inovativne značajke poput naprednog sustava kamera, moćnog A15 Bionic čipa i poboljšane trajnosti. Uživajte u besprijekornoj izvedbi, brzoj pohrani podataka te vrhunskim mogućnostima snimanja i uređivanja fotografija i videozapisa. iPhone 15 Blue 128GB je sjajan odabir za one koji traže spoj vrhunske tehnologije i estetske privlačnosti. Osvježite svoj digitalni svijet s ovim impresivnim uređajem koji će zadovoljiti i najzahtjevnije korisnike.',
    category: 'mobiteli',
  },
  {
    id: 2,
    title: 'Samsung Galaxy S23',
    price: 849.99,
    image: 'https://i.imgur.com/om4R045.jpg',
    description:
      'Dobrodošli u vrhunski mobilni svijet s Samsung Galaxy S23 u elegantnoj crnoj boji i prostranim prostorom za pohranu od 256GB. Ovaj pametni telefon donosi vrhunske značajke, uključujući napredan sustav kamera, brz i moćan procesor te visokokapacitetnu pohranu za sve vaše potrebe. S23 Black kombinira sofisticiran dizajn s visokom funkcionalnošću, pružajući vrhunsko iskustvo korisnika. Uživajte u impresivnim performansama, poboljšanoj trajnosti te bogatom ekosustavu Samsungovih inovacija. S ovim uređajem, iskusite naprednu tehnologiju spojenu s elegantnim izgledom, savršenim za one koji traže vrhunsku mobilnu platformu. Samsung Galaxy S23 Black 256GB - Vaša budućnost u pametnom telefoniranju.',
    category: 'mobiteli',
  },
  {
    id: 3,
    title: 'Laptop ACER Aspire 7',
    price: 829.99,
    image: 'https://i.imgur.com/QioYljt.jpg',
    description:
      'Upoznajte ACER Aspire 7 - prijenosno računalo koje kombinira izvanredne performanse i elegantan dizajn.Opremljen moćnim procesorom i velikim kapacitetom memorije, ovaj laptop pruža brz odziv i fluidno iskustvo rada.S tanak i moderan dizajn, Aspire 7 nudi ugodno iskustvo rada uz impresivan zaslon visoke rezolucije.Idealan je za produktivnost, kreativne projekte i igre, pružajući svestranost koja odgovara različitim potrebama korisnika.Sa snažnom kombinacijom performansi i dizajna, ACER Aspire 7 je pouzdan partner za one koji traže svestran i efikasan prijenosni računar.',
    category: 'laptopi',
  },
  {
    id: 4,
    title: 'Sony Playstation 5',
    price: 559.99,
    image: 'https://i.imgur.com/FT4Ltdj.jpg',
    description:
      'Doživite revoluciju u gamingu s PlayStation 5, vrhunskom igraćom konzolom koja podiže iskustvo igranja na potpuno novu razinu. PlayStation 5 donosi nevjerojatnu grafiku u 4K rezoluciji, brzi SSD za gotovo trenutačno učitavanje igara, te revolucionarni DualSense kontroler koji pruža senzacionalan taktički doživljaj igre. S bogatstvom ekskluzivnih naslova i podrškom za VR iskustva, PS5 je centar vrhunske zabave. Uživajte u realističnom gamingu, besprijekornom performansama i inovativnim značajkama koje čine PlayStation 5 nezaobilaznom igraćom konzolom za ljubitelje videoigara širom svijeta. Osvježite svoje iskustvo igranja s najnovijom tehnologijom uz PlayStation 5.',
    category: 'konzole',
  },
  {
    id: 5,
    title: 'Baldurs Gate 3 za PS5',
    price: 59.99,
    image: 'https://i.imgur.com/yKpyPz0.png',
    description:
      "Baldur's Gate 3, epicentar avanture u svijetu Dungeons & Dragons, pruža nevjerojatno duboko iskustvo uloge u kojem se igrači upuštaju u epsko putovanje prepuno tajni, izazova i fantastičnih bića. Razvijen od strane Larian Studios, igra oživljava bogatstvo D&D svemira uz spektakularnu grafiku, duboke narativne krivulje i inovativan sustav odlučivanja koji oblikuje priču prema igračevim akcijama. S uvjerljivim likovima, bogatim okolinama i taktičkim borbenim sustavom, Baldur's Gate 3 je nezaobilazno iskustvo za ljubitelje RPG igara, pružajući im priliku da istraže opasnosti i misterije ove izvanredne fantazijske avanture.",
    category: 'videoigre',
  },
  {
    id: 6,
    title: 'Huawei P Smart 2021',
    price: 218.99,
    image: 'https://i.imgur.com/1wGjewp.jpg',
    description: 'This is the Huawei P Smart 2021.',
    category: 'mobiteli',
  },
  {
    id: 7,
    title: 'LENOVO IdeaPad 3',
    price: 519.99,
    image: 'https://i.imgur.com/58jiTOb.jpg',
    description: 'This is the Lenovo IdeaPad 3.',
    category: 'laptopi',
  },
  {
    id: 8,
    title: 'HP 250 G8',
    price: 449.9,
    image: 'https://i.imgur.com/oEXTOPj.jpg',
    description: 'This is the HP 250 G8.',
    category: 'laptopi',
  },
  {
    id: 9,
    title: 'ASUS X540',
    price: 494.0,
    image: 'https://i.imgur.com/UXL6DIj.jpg',
    description: 'This is the ASUS X540',
    category: 'laptopi',
  },
  {
    id: 10,
    title: 'Samsung Galaxy A34',
    price: 389.99,
    image: 'https://i.imgur.com/LMufbPC.jpg',
    description: 'This is Samsung Galaxy A34.',
    category: 'mobiteli',
  },
  {
    id: 11,
    title: "TV 43' Samsung 43CU",
    price: 549.99,
    image: 'https://i.imgur.com/ogJnD8F.png',
    description: "This is 43' Samsung TV 43CU.",
    category: 'televizori',
  },
  {
    id: 12,
    title: 'HP DeskJet 2710e',
    price: 49.99,
    image: 'https://i.imgur.com/gLyOWit.jpg',
    description: 'This is HP DeskJet 2710e.',
    category: 'printeri',
  },
  {
    id: 13,
    title: 'Tinta HP 305 Black',
    price: 15.99,
    image: 'https://i.imgur.com/pqN63IR.jpg',
    description: 'This is HP 305 Black ink.',
    category: 'printeri',
  },
  {
    id: 14,
    title: 'Tipkovnica Razer Ornata',
    price: 56.99,
    image: 'https://i.imgur.com/DaUOHPZ.jpg',
    description: 'This is the Razer Ornata keyboard.',
    category: 'tipkovnice',
  },
  {
    id: 15,
    title: 'Miš Razer DeathAdder',
    price: 37.99,
    image: 'https://i.imgur.com/G0EITkg.jpg',
    description: 'This is the Razer DeathAdder mouse.',
    category: 'tipkovnice',
  },
  {
    id: 16,
    title: 'USB Kingston 64GB',
    price: 5.99,
    image: 'https://i.imgur.com/oM4Gitc.jpg',
    description: 'This is the USB Kingston 64GB.',
    category: 'pohrana',
  },
  {
    id: 17,
    title: 'PS5 Dualsense Controller',
    price: 69.99,
    image: 'https://i.imgur.com/pSFQxDI.png',
    description: 'This is the PS5 Dualsense Controller.',
    category: 'konzole',
  },
  {
    id: 18,
    title: 'Router ASUS 4G',
    price: 79.99,
    image: 'https://i.imgur.com/0EG2wrH.jpg',
    description: 'This is the ASUS 4G Router.',
    category: 'mreznaoprema',
  },
  {
    id: 19,
    title: 'Nintendo Switch',
    price: 369.99,
    image: 'https://i.imgur.com/NAaHK0U.jpg',
    description: 'This is the Nintendo Switch.',
    category: 'konzole',
  },
  {
    id: 20,
    title: 'The Last of Us za PS5',
    price: 69.99,
    image: 'https://i.imgur.com/jOm43U4.png',
    description: 'This is the videogame The Last of Us for the PS5.',
    category: 'videoigre',
  },
]

export default products
